### ISSUE TITLE
Embedded images render larger than container

### ISSUE THREAD

**Issue by jh3y** [jh3y/tyto#67]
### Issue summary
If an `<img>` tag is embedded using `markdown` and the image is larger than the container, it will simply render larger than the container.

### Expected behavior
It should have a maximum width of the container.

### Browser used
Chrome.

### Steps to reproduce
Add any large image to a task.

### Solution
```css
.tyto-task__description img {
  max-width: 100%;
}
```
